### ISSUE TITLE
Cannot find module 'react-easy-universal'

### ISSUE THREAD

**Issue by PetarIvancevic** [keystonejs/react-easy-universal#14]
Cannot find module 'react-easy-universal'
Am I doing something wrong? Do I need to require it in a special way rather than just:
`import universal from 'react-easy-universal';`
or
`var reactEasyUniversal = require('react-easy-universal');`

**Comment by cannap** [comment]
i dont tested this repo right now but you have npm installed before?

**Comment by ericelliott** [comment]
[This open PR is about to land](https://github.com/keystonejs/react-easy-universal/pull/13/files) which separates the client & server modules to save on the client bundle payload, so this is about to change. Watch this space, or feel free to experiment with the new branch.
