### ISSUE TITLE
Move to TravisCI

### ISSUE THREAD

**Issue by LorbusChris** [keystonejs/react-easy-universal#21]
discussion of this: https://github.com/keystonejs/react-easy-universal/pull/5#issuecomment-180869840

**Comment by ericelliott** [comment]
:+1:

**Comment by LorbusChris** [comment]
@ericelliott As storing encrypted env vars is only possible with Travis, should only it do the testing with SauceLabs then (i.e. not Circle)?

See #22. At the moment it uses Sauce on both, Travis and Circle. I could remove or comment out the SauceLabs settings on Circle, though. Probably makes sense...what are your thoughts on this?

**Comment by LorbusChris** [comment]
@ericelliott as discussed on gitter, I'd be happy to take on the opportunity and help maintain this repo. :smiley:
